Add alpha beta steps on processes
nextcloud/groupware pull request #48
Opened 2022-07-15 13:15 UTC by GretaD

Signed-off-by: greta <gretadoci@gmail.com>

2022-07-18 08:52 UTC, miaulalala approved these changes

2022-08-08 08:37 UTC, ChristophWurst requested changes

2022-08-08 08:37 UTC, ChristophWurst commented on processes/app_release.md
> +#### alpha and beta have the same steps, just replace alpha with beta on steps below
```suggestion
### Alpha and beta have the same steps, just replace alpha with beta on steps below
```

2022-08-08 08:37 UTC, ChristophWurst commented on processes/app_release.md
> +   2.1. Do `git log v1.2.3..HEAD --oneline | grep -v "Merge "` - v1.2.3 is the last release
```suggestion
2. Change info.xml and CHANGELOG.MD
   2.1. Do `git log v1.2.3..HEAD --oneline | grep -v "Merge "` - v1.2.3 is the last release
```

2022-08-08 08:37 UTC, ChristophWurst commented on processes/app_release.md
> +   6.3 The package will be automatically built and attached to the new release
```suggestion
6. We go to the release's repository tags page, e.g. https://github.com/nextcloud-releases/mail/tags
   6.1 On the draft we add the tag we created, add the change log and publish the release
   6.2 Wait a few minutes for the automation to build the app
   6.3 The package will be automatically built and attached to the new release
```

2022-08-09 11:24 UTC, ChristophWurst approved these changes

2022-08-11 17:45 UTC, merged